version: "3.7"
services:
  bot:
    image: ghcr.io/freemanoid/tg-torrent-bot:1.0.2@sha256:a884320bd1065f0ced47fcb434a704ac26a7f34446468c630fb5f35dd5fd2b09
    restart: on-failure
    stop_grace_period: 30s
    env_file: ${APP_DATA_DIR}/.env
    volumes:
      - ${APP_DATA_DIR}/data:/data
    container_name: freemanoid-tg-torrent-bot_bot_1
