version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: freemanoid-tg-torrent-bot_bot_1
      APP_PORT: 8542
    container_name: freemanoid-tg-torrent-bot_app_proxy_1
  bot:
    image: ghcr.io/freemanoid/tg-torrent-bot:1.4.0@sha256:f5919de4edaf2cca10c4806aececa49db2331be52ebd0ad1e79947bd7d13c420
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data:/data
    container_name: freemanoid-tg-torrent-bot_bot_1
