version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: freemanoid-tg-torrent-bot_bot_1
      APP_PORT: 8542
    container_name: freemanoid-tg-torrent-bot_app_proxy_1
  bot:
    image: ghcr.io/freemanoid/tg-torrent-bot:1.9.0@sha256:909a48bd013f0a04d31aa105c3bb327dc2f93df65d278a45bf0d09437f3443aa
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data:/data
    container_name: freemanoid-tg-torrent-bot_bot_1
